# Generated by Django 5.0.9 on 2026-09-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_ingested', models.IntegerField(default=0)),
                ('anomalies_found', models.IntegerField(default=0)),
                ('forecasts_generated', models.IntegerField(default=0)),
                ('recommendations_generated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('external_id', models.CharField(help_text='Account ID / Subscription ID / Project ID', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('actual_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('deviation_pct', models.FloatField()),
                ('score', models.FloatField(help_text='Isolation Forest anomaly score (lower = more anomalous)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('method', models.CharField(default='isolation_forest', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='costs.cloudaccount')),
            ],
            options={
                'ordering': ['-date', '-deviation_pct'],
                'unique_together': {('account', 'service', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('service', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=60)),
                ('resource_id', models.CharField(max_length=120)),
                ('instance_type', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('usage_quantity', models.FloatField(blank=True, null=True)),
                ('avg_utilization_pct', models.FloatField(blank=True, null=True)),
                ('workload_tag', models.CharField(blank=True, default='', max_length=80)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='costs.cloudaccount')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'service', 'date'], name='costs_costr_account_e64bed_idx')],
                'unique_together': {('account', 'date', 'service', 'resource_id')},
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('predicted_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=4, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=4, max_digits=12)),
                ('model_used', models.CharField(default='prophet', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='costs.cloudaccount')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('account', 'service', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120)),
                ('resource_id', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=60)),
                ('action', models.CharField(choices=[('downsize', 'Downsize'), ('terminate', 'Terminate idle resource')], default='downsize', max_length=20)),
                ('current_instance_type', models.CharField(blank=True, default='', max_length=60)),
                ('recommended_instance_type', models.CharField(blank=True, default='', max_length=60)),
                ('avg_utilization_pct', models.FloatField(blank=True, null=True)),
                ('current_monthly_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_savings_pct', models.FloatField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('terraform_script', models.TextField(blank=True, default='')),
                ('terraform_file_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='costs.cloudaccount')),
            ],
            options={
                'ordering': ['-estimated_monthly_savings'],
                'unique_together': {('account', 'resource_id')},
            },
        ),
    ]
