# Generated by Django 5.0.9 on 2026-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='estimated_annual_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='projected_utilization_pct',
            field=models.FloatField(blank=True, help_text='Utilisation the resource would run at after applying this recommendation', null=True),
        ),
    ]
